test-pathfinder: main.cpp TestCase.cpp TestStateStar.cpp
		c++ -std=c++11 -stdlib=libc++ main.cpp TestCase.cpp TestStateStar.cpp ../lib/Node.cpp ../lib/Point2D.cpp ../lib/Path.cpp ../lib/Graph.cpp -o main
